name: noteshare_flutter
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.0.0
  file_picker: ^8.0.0
  image_picker: ^1.0.0
  camera: ^0.11.1

  http: ^1.2.0
  http_parser: ^4.0.2
  mime: ^1.0.4

  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8

  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Noto
  #     fonts:
  #       - asset: fonts/NotoSans-Regular.ttf
  #       - asset: fonts/NotoSans-Bold.ttf
  #         weight: 700
